// Pricing is now served from the backend API via /api/pricing/by-type/:courseTypeKey
// See: services/hooks/useLessonPricing.ts and components/courses/components/PricingTable.tsx

export const constants = {
  BUTTONT_TEXT: 'register',
  BUTTONT__INFO: 'forRegisteredUsers',
};

export const getPaymentContent = (usdExchangeRate: number) => {
  const getPriceHy = (amdPrice: number) => {
    const usdPrice = Math.round(amdPrice / usdExchangeRate);
    const formattedAmd = amdPrice >= 10000 ? `${amdPrice / 1000}.000` : amdPrice.toString();
    return `${formattedAmd} ՀՀ դրամ ($${usdPrice})`;
  };

  const getPriceRu = (amdPrice: number) => {
    const usdPrice = Math.round(amdPrice / usdExchangeRate);
    const formattedAmd = amdPrice >= 10000 ? `${amdPrice / 1000}.000` : amdPrice.toString();
    return `${formattedAmd} AMD ($${usdPrice})`;
  };

  const getPriceEn = (amdPrice: number) => {
    const usdPrice = Math.round(amdPrice / usdExchangeRate);
    const formattedAmd = amdPrice >= 10000 ? `${amdPrice / 1000}.000` : amdPrice.toString();
    return `${formattedAmd} AMD ($${usdPrice})`;
  };

  return {
    ru: `<p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">1. Базовый курс</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Уровни: A, B, C<br>Продолжительность урока: 45 минут<br>Стоимость урока: ${getPriceRu(10000)}<br>Обучение строится по индивидуальной программе</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2. Углублённый курс</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Продолжительность курса определяется индивидуальными целями ученика.<br>Длительность уроков может быть: 30, 45 или 60 минут.<br><br>30 минут — ${getPriceRu(8000)}<br>45 минут — ${getPriceRu(10000)}<br>60 минут — ${getPriceRu(12000)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3. Индивидуальные занятия</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Длительность уроков может быть: 30, 45 или 60 минут.<br><br>30 минут — ${getPriceRu(8000)}<br>45 минут — ${getPriceRu(10000)}<br>60 минут — ${getPriceRu(12000)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">4. Групповые занятия (цены указаны за одного человека)</span></strong></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2 человека</span></strong><br><span style="color: rgb(0, 0, 0)">30 минут — ${getPriceRu(5600)}<br>45 минут — ${getPriceRu(7200)}<br>60 минут — ${getPriceRu(8800)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3 человека</span></strong><br><span style="color: rgb(0, 0, 0)">30 минут — ${getPriceRu(4800)}<br>45 минут — ${getPriceRu(6000)}<br>60 минут — ${getPriceRu(7200)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">5. Скидки</span></strong></p><ul><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">5% — при оплате всего уровня/курса</span></p></li><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">3% — при оплате сразу за 8 уроков</span></p></li></ul><br><p style="text-align: justify"><small><i>* Цены в долларах США рассчитаны по текущему курсу ЦБ РА: 1 USD = ${usdExchangeRate} AMD</i></small></p>`,

    en: `<p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">1. Main Course</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Levels: A, B, C<br>Lesson duration: 45 minutes<br>Lesson price: ${getPriceEn(10000)}<br>Training follows individual programs</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2. Advanced Course</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Course length depends on the student’s individual goals.<br>Lesson duration can be 30, 45, or 60 minutes.<br><br>30 minutes — ${getPriceEn(8000)}<br>45 minutes — ${getPriceEn(10000)}<br>60 minutes — ${getPriceEn(12000)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3. Individual Lessons</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Lesson duration can be 30, 45, or 60 minutes.<br><br>30 minutes — ${getPriceEn(8000)}<br>45 minutes — ${getPriceEn(10000)}<br>60 minutes — ${getPriceEn(12000)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">4. Group Lessons (prices are per student)</span></strong></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2 students</span></strong><br><span style="color: rgb(0, 0, 0)">30 minutes — ${getPriceEn(5600)}<br>45 minutes — ${getPriceEn(7200)}<br>60 minutes — ${getPriceEn(8800)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3 students</span></strong><br><span style="color: rgb(0, 0, 0)">30 minutes — ${getPriceEn(4800)}<br>45 minutes — ${getPriceEn(6000)}<br>60 minutes — ${getPriceEn(7200)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">5. Discounts</span></strong></p><ul><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">5% — for full level/course payment</span></p></li><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">3% — for advance payment of 8 lessons</span></p></li></ul><br><p style="text-align: justify"><small><i>* Prices in USD are calculated at the current CBA exchange rate: 1 USD = ${usdExchangeRate} AMD</i></small></p>`,

    hy: `<p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">1. Հիմնական դասընթաց</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Մակարդակներ: A, B, C<br>Դասի տևողություն: 45 րոպե<br>Դասի արժեք: ${getPriceHy(10000)}<br>Ուսուցումը իրականացվում է անհատական ծրագրերով</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2. Խորացված դասընթաց</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Դասընթացի տևողությունը որոշվում է ուսանողի նպատակների հիման վրա:<br>Դասերի տևողությունը կարող է լինել 30, 45 կամ 60 րոպե:<br><br>30 րոպե — ${getPriceHy(8000)}<br>45 րոպե — ${getPriceHy(10000)}<br>60 րոպե — ${getPriceHy(12000)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3. Անհատական դասեր</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Դասերի տևողությունը կարող է լինել 30, 45 կամ 60 րոպե:<br><br>30 րոպե — ${getPriceHy(8000)}<br>45 րոպե — ${getPriceHy(10000)}<br>60 րոպե — ${getPriceHy(12000)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">4. Խմբային դասեր (տվյալները նշված են մեկ ուսանողի համար)</span></strong></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2 ուսանող</span></strong><br><span style="color: rgb(0, 0, 0)">30 րոպե — ${getPriceHy(5600)}<br>45 րոպե — ${getPriceHy(7200)}<br>60 րոպե — ${getPriceHy(8800)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3 ուսանող</span></strong><br><span style="color: rgb(0, 0, 0)">30 րոպե — ${getPriceHy(4800)}<br>45 րոպե — ${getPriceHy(6000)}<br>60 րոպե — ${getPriceHy(7200)}</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">5. Զեղչեր</span></strong></p><ul><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">5% — ամբողջ մակարդակի/կուրսի վճարման դեպքում</span></p></li><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">3% — 8 դասի նախավճարի դեպքում</span></p></li></ul><br><p style="text-align: justify"><small><i>* ԱՄՆ դոլարով գները հաշվարկված են ՀՀ ԿԲ ներկայիս փոխարժեքով՝ 1 USD = ${usdExchangeRate} ՀՀ դրամ</i></small></p>`,
  };
};

