export const constants = {
  BUTTONT_TEXT: 'register',
  BUTTONT__INFO: 'forRegisteredUsers',
};

export const PAYMENT = {
  ru: '<p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">1. Базовый курс</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Уровни: A, B, C<br>Продолжительность урока: 45 минут<br>Стоимость урока: $25<br>Обучение строится по индивидуальной программе</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2. Углублённый курс</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Продолжительность курса определяется индивидуальными целями ученика.<br>Длительность уроков может быть: 30, 45 или 60 минут.<br><br>30 минут — $20<br>45 минут — $25<br>60 минут — $30</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3. Индивидуальные занятия</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Длительность уроков может быть: 30, 45 или 60 минут.<br><br>30 минут — $20<br>45 минут — $25<br>60 минут — $30</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">4. Групповые занятия (цены указаны за одного человека)</span></strong></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2 человека</span></strong><br><span style="color: rgb(0, 0, 0)">30 минут — $14<br>45 минут — $18<br>60 минут — $22</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3 человека</span></strong><br><span style="color: rgb(0, 0, 0)">30 минут — $12<br>45 минут — $15<br>60 минут — $18</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">5. Скидки</span></strong></p><ul><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">5% — при оплате всего уровня/курса</span></p></li><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">3% — при оплате сразу за 8 уроков</span></p></li></ul>',

  en: '<p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">1. Main Course</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Levels: A, B, C<br>Lesson duration: 45 minutes<br>Lesson price: $25<br>Training follows individual programs</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2. Advanced Course</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Course length depends on the student’s individual goals.<br>Lesson duration can be 30, 45, or 60 minutes.<br><br>30 minutes — $20<br>45 minutes — $25<br>60 minutes — $30</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3. Individual Lessons</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Lesson duration can be 30, 45, or 60 minutes.<br><br>30 minutes — $20<br>45 minutes — $25<br>60 minutes — $30</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">4. Group Lessons (prices are per student)</span></strong></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2 students</span></strong><br><span style="color: rgb(0, 0, 0)">30 minutes — $14<br>45 minutes — $18<br>60 minutes — $22</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3 students</span></strong><br><span style="color: rgb(0, 0, 0)">30 minutes — $12<br>45 minutes — $15<br>60 minutes — $18</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">5. Discounts</span></strong></p><ul><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">5% — for full level/course payment</span></p></li><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">3% — for advance payment of 8 lessons</span></p></li></ul>',

  hy: '<p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">1. Հիմնական դասընթաց</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Մակարդակներ: A, B, C<br>Դասի տևողություն: 45 րոպե<br>Դասի արժեք: $25<br>Ուսուցումը իրականացվում է անհատական ծրագրերով</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2. Խորացված դասընթաց</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Դասընթացի տևողությունը որոշվում է ուսանողի նպատակների հիման վրա:<br>Դասերի տևողությունը կարող է լինել 30, 45 կամ 60 րոպե:<br><br>30 րոպե — $20<br>45 րոպե — $25<br>60 րոպե — $30</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3. Անհատական դասեր</span></strong></p><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Դասերի տևողությունը կարող է լինել 30, 45 կամ 60 րոպե:<br><br>30 րոպե — $20<br>45 րոպե — $25<br>60 րոպե — $30</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">4. Խմբային դասեր (տվյալները նշված են մեկ ուսանողի համար)</span></strong></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">2 ուսանող</span></strong><br><span style="color: rgb(0, 0, 0)">30 րոպե — $14<br>45 րոպե — $18<br>60 րոպե — $22</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">3 ուսանող</span></strong><br><span style="color: rgb(0, 0, 0)">30 րոպե — $12<br>45 րոպե — $15<br>60 րոպե — $18</span></p><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">5. Զեղչեր</span></strong></p><ul><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">5% — ամբողջ մակարդակի/կուրսի վճարման դեպքում</span></p></li><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">3% — 8 դասի նախավճարի դեպքում</span></p></li></ul>',
};
